// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text     string `json:"text"`
	UserID   string `json:"userId"`
	Done     *bool  `json:"done,omitempty"`
	UserName string `json:"userName"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User string `json:"user"`
}
